# -*- coding: utf-8 -*-
"""Codealpha_Credit scoring model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNmDSLL3Zc3dhcB5kZFPbyFFOJE4FnlB
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

import zipfile
import os

zip_file_path = '/content/archive.zip'
extract_dir = '/content/extracted_data'

os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print(f"Archive extracted to: {extract_dir}")

print("Contents of the extracted directory:")
for root, dirs, files in os.walk(extract_dir):
    for name in files:
        print(os.path.join(root, name))
    for name in dirs:
        print(os.path.join(root, name))

data.info()

data.describe(include='all')

print("\nValue counts for 'Saving accounts':")
print(data['Saving accounts'].value_counts(dropna=False))

print("\nValue counts for 'Checking account':")
print(data['Checking account'].value_counts(dropna=False))

data = data.drop('Unnamed: 0', axis=1)
print("DataFrame after dropping 'Unnamed: 0' column:")
print(data.head())

print("\nValue counts for 'Saving accounts':")
print(data['Saving accounts'].value_counts(dropna=False))

print("\nValue counts for 'Checking account':")
print(data['Checking account'].value_counts(dropna=False))

saving_accounts_mode = data['Saving accounts'].mode()[0]
data['Saving accounts'] = data['Saving accounts'].fillna(saving_accounts_mode)

checking_account_mode = data['Checking account'].mode()[0]
data['Checking account'] = data['Checking account'].fillna(checking_account_mode)

print("Missing values after imputation:")
print(data[['Saving accounts', 'Checking account']].isnull().sum())

categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    print(f"Column '{col}' encoded with mapping: {list(le.classes_)}")

print("\nDataFrame after Label Encoding:")
print(data.head())

print("Unique values in 'Job' (potential target variable):")
print(data['Job'].unique())

X = data.drop('Job', axis=1)
y = data['Job']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("RandomForestClassifier trained successfully.")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    print(f"Column '{col}' encoded with mapping: {list(le.classes_)}")

print("\nDataFrame after Label Encoding:")
print(data.head())

print("Unique values in 'Job' (potential target variable):")
print(data['Job'].unique())

X = data.drop('Job', axis=1)
y = data['Job']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    print(f"Column '{col}' encoded with mapping: {list(le.classes_)}")

print("\nDataFrame after Label Encoding:")
print(data.head())

print("Unique values in 'Job' (potential target variable):")
print(data['Job'].unique())

X = data.drop('Job', axis=1)
y = data['Job']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    print(f"Column '{col}' encoded with mapping: {list(le.classes_)}")

print("\nDataFrame after Label Encoding:")
print(data.head())

print("Unique values in 'Job' (potential target variable):")
print(data['Job'].unique())

X = data.drop('Job', axis=1)
y = data['Job']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

saving_accounts_mode = data['Saving accounts'].mode()[0]
data['Saving accounts'] = data['Saving accounts'].fillna(saving_accounts_mode)

checking_account_mode = data['Checking account'].mode()[0]
data['Checking account'] = data['Checking account'].fillna(checking_account_mode)

print("Missing values after imputation:")
print(data[['Saving accounts', 'Checking account']].isnull().sum())

saving_accounts_mode = data['Saving accounts'].mode()[0]
data['Saving accounts'] = data['Saving accounts'].fillna(saving_accounts_mode)

checking_account_mode = data['Checking account'].mode()[0]
data['Checking account'] = data['Checking account'].fillna(checking_account_mode)

print("Missing values after imputation:")
print(data[['Saving accounts', 'Checking account']].isnull().sum())

saving_accounts_mode = data['Saving accounts'].mode()[0]
data['Saving accounts'] = data['Saving accounts'].fillna(saving_accounts_mode)

checking_account_mode = data['Checking account'].mode()[0]
data['Checking account'] = data['Checking account'].fillna(checking_account_mode)

print("Missing values after imputation:")
print(data[['Saving accounts', 'Checking account']].isnull().sum())